module.exports = {
    rcodeNum: {
        0: "No Error",
        1: "Format Error",
        2: "Server Failure",
        3: "Non-Existent Domain",
        4: "Not Implemented",
        5: "Query Refused",
        6: "Name Exists when it should not",
        7: "RR Set Exists when it should not",
        8: "RR Set that should exist does not",
        9: "Server Not Authoritative for zone or Not Authorized",
        10: "Name not contained in zone",
        11: "DSO-TYPE Not Implemented",
        16: "Bad OPT Version or TSIG Signature Failure",
        17: "Key not recognized",
        18: "Signature out of time window",
        19: "Bad TKEY Mode",
        20: "Duplicate key name",
        21: "Algorithm not supported",
        22: "Bad Truncation",
        23: "Bad/missing Server Cookie",
    },
    rcodeID: {
        NoError: ["No Error", 0],
        FormErr: ["Format Error", 1],
        ServFail: ["Server Failure", 2],
        NXDomain: ["Non-Existent Domain", 3],
        NotImp: ["Not Implemented", 4],
        Refused: ["Query Refused", 5],
        YXDomain: ["Name Exists when it should not", 6],
        YXRRSet: ["RR Set Exists when it should not", 7],
        NXRRSet: ["RR Set that should exist does not", 8],
        NotAuth: ["Server Not Authoritative for zone or Not Authorized", 9],
        NotZone: ["Name not contained in zone", 10],
        DSOTYPENI: ["DSO-TYPE Not Implemented", 11],
        BADVERS: ["Bad OPT Version", 16],
        BADSIG: ["TSIG Signature Failure", 16],
        BADKEY: ["Key not recognized", 17],
        BADTIME: ["Signature out of time window", 18],
        BADMODE: ["Bad TKEY Mode", 19],
        BADNAME: ["Duplicate key name", 20],
        BADALG: ["Algorithm not supported", 21],
        BADTRUNC: ["Bad Truncation", 22],
        BADCOOKIE: ["Bad/missing Server Cookie", 23],
    },
    http: {
        400: "DNS query not specified or too small.",
        413: "DNS query is larger than maximum allowed DNS message size.",
        415: "Unsupported content type.",
        504: "Resolver timeout while waiting for the query response.",
    },
}
